version: '3'

services:
  go-app:
    container_name: go-app
    image: mannyhq/go-app:1.0.0
    build: .
    networks:
      - mynetwork
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@go_db:5432/manuel?sslmode=disable" #host=go_db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    networks:
      - mynetwork
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: manuel
    ports:
      - "5435:5435"
    volumes:
      - pgdata:/var/lib/postgresql/data
  proxy:
    build: proxy
    networks:
      - mynetwork
    ports:
      - 8080:80
    depends_on: 
      - go-app

volumes:  
  pgdata: {}

networks:
  mynetwork:
    driver: bridge
